//The Fibonacci Series is a mathematical series that starts with 0 and 1 and is generated by adding the two preceding numbers to generate the next one.Write a c program to find the fibboncci series


#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

int main() {
    int a,b,n,i,result;

    /*printf("Enter the number of terms :");*/
    scanf("%d",&n);
    a=0;
    b=1;
    for(i=0;i<n;i++)
    {
        printf("%d ",a);
        result=a+b;
        a=b;
        b=result;
    }
        
    return 0;
}
